spring.application.name=shop_BE

spring.datasource.url=jdbc:mariadb://localhost:3306/shop
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationInShopApplication2024
jwt.expiration=86400000
jwt.refresh-expiration=604800000
